version: "3"

services:
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URL: "mongodb://mongo:27017/your-database-name"
      JWT_SECRET_KEY: your-secret-key
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BASE_URL: "http://server:5001"
    depends_on:
      - server

  mongo:
    image: mongo
    ports:
      - "27018:27017"
